#!/usr/bin/env python3
"""
skills.rebuild — coverage-aware rebuild of the nutrition analysis.

Stdlib only. No pyfooda, no pandas, no network. Reads:

    data/purchases_enriched.csv   raw purchase rows (product_name, price, date, ...)
    skills/food_table.json        per-100g nutrient profiles + units

Writes:

    public/report.json            the analysis dataset
    public/index.html             mobile-first report (generated by report_html.py)

What differs from the legacy pipeline (skills/nutrition_report.py):

  1. Duplicate receipt images are collapsed; each transaction counts once.
  2. Quantity is re-derived from the printed product name ONLY. No 100 g
     fallback, no price->weight guess, no typical-unit-weight table.
  3. Volumes stay volumes. ml is never assumed to equal g.
  4. No 5x-DRV nutrient suppression. Suspicious density is reported, not deleted.
  5. No IQR outlier deletion of whole trips.
  6. Verified-wrong mappings are quarantined with a visible reason.
  7. Every headline number carries its own coverage figure.

Run:  python3 -m skills.rebuild
"""

from __future__ import annotations

import csv
import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PURCHASES_CSV = ROOT / "data" / "purchases_enriched.csv"
FOOD_TABLE = Path(__file__).resolve().parent / "food_table.json"
PUBLIC_DIR = ROOT / "public"

KCAL_NORM = 2500

# ── Receipt deduplication ────────────────────────────────────────────────────
# Confirmed by SHA-256 over data/delhaize/*.jpg: four image pairs are byte
# identical. Keep one canonical CSV per pair, record the other as an alias.
DUPLICATE_ALIASES: dict[str, str] = {
    "2024_31_08.csv": "2024_08_31.csv",   # filename month/day swapped
    "2024_03_30.csv": "2024_03_25.csv",   # same image, two filename dates
    "2024_03_25_b.csv": "2024_03_24.csv",  # same image
    "2024_04_25_b.csv": "2024_04_25.csv",  # same image
}

# ── Quarantined mappings ─────────────────────────────────────────────────────
# Manually verified as wrong. Quarantined rows stay visible in the report and
# count against coverage; they never contribute nutrients.
QUARANTINE: dict[str, str] = {
    "6X33CL SCH GINGER":
        "Ginger ale (6x33 cl beverage) mapped to pure ginger root, and 1.98 L "
        "of liquid counted as 1980 g of spice.",
    "190G THIN ROMARIN":
        "Rosemary crackers mapped to pure rosemary herb.",
    "PAIN DE VIANDE":
        "Meatloaf mapped to bread.",
    "MENTHE GROS PO BIO":
        "Fresh mint mapped to creme-de-menthe liqueur.",
    "40G DLL PATE NOI":
        "Pate mapped to pie crust, and a 40 g package recorded as 400 g.",
    "MINT-PIMENTS MIX":
        "Chilli-pepper mix mapped to pure mint.",
    "MINT GRENAILLES 50":
        "Baby potatoes ('grenailles') mapped to pure mint.",
    "PIZZA MOZZA PESTO":
        "Whole pizza mapped to pesto sauce.",
    "DES DE FILET THAI":
        "Diced meat fillet, Thai style, mapped to Thai tea.",
    "SAL BLE EMB 100GR":
        "Bagged lamb's-lettuce salad most likely mapped to table salt; "
        "100 g of salt is not a plausible grocery line.",
}

# Composite products whose match is the ingredient named in the label.
# Flagged for review, not removed.
COMPOSITE_HINTS = (
    "PIZZA", "SAUCE", "SOUP", "SOEP", "TART", "QUICHE", "BURGER", "NUGGET",
    "LASAG", "GRATIN", "SALADE", "SANDWICH", "WRAP", "SNACK", "BISCUIT",
    "CRACKER", "CHIPS", "GAUF", "CAKE", "MOUSSE", "GLACE", "YAOURT",
)

# ── Reference values ─────────────────────────────────────────────────────────
# EU Regulation 1169/2011 Annex XIII adult reference intakes / NRVs, defined
# against 2000 kcal, rescaled by 1.25 to the 2500 kcal normalisation used here.
# This is a NUTRIENT-DENSITY comparison for a purchase basket. It is NOT an
# adequacy or intake assessment for any person.
_EU_RI_2000 = {
    "Protein": 50.0,
    "Carbohydrate": 260.0,
    "Sugars, Total": 90.0,
    "Total fat": 70.0,
    "Fatty acids, total saturated": 20.0,
    "Sodium": 2400.0,          # 6 g salt expressed as sodium
    "Vitamin A, RAE": 800.0,
    "Vitamin D (D2 + D3)": 5.0,
    "Vitamin C": 80.0,
    "Thiamin": 1.1,
    "Riboflavin": 1.4,
    "Folate, total": 200.0,
    "Vitamin B-12": 2.5,
    "Calcium": 800.0,
    "Iron": 14.0,
    "Magnesium": 375.0,
    "Zinc": 10.0,
    "Potassium": 2000.0,
}
_NON_EU_REFERENCE = {"Fiber": 25.0}   # EFSA adequate intake, not an EU NRV
_NO_REFERENCE = {"Cholesterol"}       # no EU reference value exists

_SCALE = KCAL_NORM / 2000.0
REFERENCE = {k: v * _SCALE for k, v in _EU_RI_2000.items()}
REFERENCE.update({k: v * _SCALE for k, v in _NON_EU_REFERENCE.items()})
REFERENCE_KIND = {k: "EU NRV/RI" for k in _EU_RI_2000}
REFERENCE_KIND.update({k: "EFSA AI (not an EU NRV)" for k in _NON_EU_REFERENCE})

NUTRIENT_IT = {
    "Protein": "Proteine",
    "Carbohydrate": "Carboidrati",
    "Fiber": "Fibre",
    "Sugars, Total": "Zuccheri totali",
    "Total fat": "Grassi totali",
    "Fatty acids, total saturated": "Grassi saturi",
    "Cholesterol": "Colesterolo",
    "Calcium": "Calcio",
    "Iron": "Ferro",
    "Magnesium": "Magnesio",
    "Potassium": "Potassio",
    "Sodium": "Sodio",
    "Zinc": "Zinco",
    "Vitamin A, RAE": "Vitamina A",
    "Vitamin C": "Vitamina C",
    "Vitamin D (D2 + D3)": "Vitamina D",
    "Vitamin B-12": "Vitamina B12",
    "Folate, total": "Folati",
    "Thiamin": "Tiamina (B1)",
    "Riboflavin": "Riboflavina (B2)",
    "Energy": "Energia",
}

NUTRIENT_ORDER = [
    "Protein", "Carbohydrate", "Fiber", "Sugars, Total", "Total fat",
    "Fatty acids, total saturated", "Cholesterol", "Calcium", "Iron",
    "Magnesium", "Potassium", "Sodium", "Zinc", "Vitamin A, RAE",
    "Vitamin C", "Vitamin D (D2 + D3)", "Vitamin B-12", "Folate, total",
    "Thiamin", "Riboflavin",
]

# ── Receipt line classification ──────────────────────────────────────────────
# The legacy pipeline never classified line types, so receipt totals, loyalty
# balances and payment lines were counted as purchases. That inflated the row
# denominator (and put a 6096.00 loyalty-point balance into "spend").
_METADATA_PATTERNS = (
    r"^TOTAA?L", r"SOUS[- ]?TOTAL", r"SUBTOTAA?L", r"^TOT\b",
    r"SOLDE DE POINTS", r"\bPOINTS\b", r"PUNTEN",
    r"CHEQ", r"CHEQUE", r"BANCONTACT", r"MAESTRO", r"\bVISA\b", r"BETAALD",
    r"ESPECES", r"CONTANT", r"\bCASH\b", r"PAIEMENT", r"BETALING",
    r"\bBTW\b", r"\bTVA\b", r"\bTAX\b", r"\bHTVA\b",
    r"KORTING", r"REMISE", r"RISTOURNE", r"REDUCTION",
    r"^SN\s*\d", r"^GS\s*:", r"^EUR\b", r"CARTE\b", r"KLANTEN", r"XTRA",
    r"NOMBRE D ARTICLES", r"AANTAL ARTIKELEN", r"^A PAYER", r"TE BETALEN",
    r"^\d+[.,]?\d*\s*KG\s*X$", r"^\d{1,6}$", r"^$",
)
_METADATA_RE = re.compile("|".join(_METADATA_PATTERNS), re.I)


def classify_line(name: str, price: float | None) -> str:
    """'metadata' for totals / payment / loyalty lines, else 'product'."""
    text = (name or "").strip().upper()
    if not text:
        return "metadata"
    if _METADATA_RE.search(text):
        return "metadata"
    # A grocery line item above EUR 100 on a Belgian supermarket receipt is a
    # total or a payment instrument, not a product.
    if price is not None and price >= 100:
        return "metadata"
    return "product"


# ── Quantity parsing ─────────────────────────────────────────────────────────

_MULTIPACK = re.compile(
    r"(?<!\d)(\d{1,2})\s*[X\*]\s*(\d+(?:[.,]\d+)?)\s*(KG|GR?|ML|CL|L)(?![A-Z])",
    re.I,
)
_SINGLE = re.compile(
    r"(?<![\dX*])(\d+(?:[.,]\d+)?)\s*(KG|GR?|ML|CL|L)(?![A-Z])",
    re.I,
)

_MASS_TO_G = {"G": 1.0, "GR": 1.0, "KG": 1000.0}
_VOL_TO_ML = {"ML": 1.0, "CL": 10.0, "L": 1000.0}


def parse_quantity(name: str) -> dict:
    """Derive quantity from the printed label text only.

    Returns {kind, amount, unit, method, text} where kind is 'mass', 'volume'
    or 'unknown'. Multipacks are resolved before single-unit weights so that
    '6X33CL' yields 1980 ml and never 33 ml.
    """
    text = (name or "").upper().replace(" ", " ")

    m = _MULTIPACK.search(text)
    if m:
        count = int(m.group(1))
        value = float(m.group(2).replace(",", "."))
        unit = m.group(3).upper()
        if unit in _MASS_TO_G:
            return {"kind": "mass", "amount": count * value * _MASS_TO_G[unit],
                    "unit": "g", "method": "label_multipack", "text": m.group(0)}
        return {"kind": "volume", "amount": count * value * _VOL_TO_ML[unit],
                "unit": "ml", "method": "label_multipack", "text": m.group(0)}

    m = _SINGLE.search(text)
    if m:
        value = float(m.group(1).replace(",", "."))
        unit = m.group(2).upper()
        if unit in _MASS_TO_G:
            return {"kind": "mass", "amount": value * _MASS_TO_G[unit],
                    "unit": "g", "method": "label_single", "text": m.group(0)}
        return {"kind": "volume", "amount": value * _VOL_TO_ML[unit],
                "unit": "ml", "method": "label_single", "text": m.group(0)}

    return {"kind": "unknown", "amount": None, "unit": None,
            "method": "not_on_label", "text": None}


# ── Build ────────────────────────────────────────────────────────────────────

def load_food_table() -> tuple[dict, dict]:
    data = json.loads(FOOD_TABLE.read_text(encoding="utf-8"))
    return data["foods"], data["units"]


def build_items(foods: dict) -> list[dict]:
    """One record per receipt line, with full provenance for its exclusion.

    Two quantity tiers are kept side by side:
      observed  – read off the printed label ("190G", "6X33CL")
      declared  – the legacy pipeline's estimate (typical unit weight, price
                  guess, hand-entered grams). An estimate, not a measurement.
    The headline uses observed only; 'declared' drives the sensitivity view.
    """
    items: list[dict] = []
    with PURCHASES_CSV.open(encoding="utf-8") as fh:
        for raw in csv.DictReader(fh):
            src = raw["source_file"]
            name = (raw["product_name"] or "").strip()
            food = (raw["pyfooda_name"] or "").strip()
            action = raw["llm_action"]

            try:
                price = float(raw["price"])
            except (TypeError, ValueError):
                price = None

            try:
                legacy_g = float(raw.get("grams_in_name") or "")
            except (TypeError, ValueError):
                legacy_g = None

            line_type = classify_line(name, price)
            qty = parse_quantity(name)
            issues: list[str] = []

            duplicate_of = DUPLICATE_ALIASES.get(src)
            if duplicate_of:
                issues.append("duplicate_receipt")

            # Quantity used only in the "include estimates" sensitivity mode.
            declared_g = None
            if qty["kind"] != "mass" and legacy_g and legacy_g > 0:
                declared_g = legacy_g
                issues.append("quantity_estimated_not_observed")

            if line_type == "metadata":
                state = "receipt_metadata"
            elif action != "match" or not food:
                state = "not_food_or_unmatched"
            elif name in QUARANTINE:
                state = "quarantined"
                issues.append("bad_mapping")
            elif food not in foods:
                state = "no_food_record"
                issues.append("missing_food_record")
            elif qty["kind"] == "volume":
                state = "volume_no_density"
                issues.append("volume_without_official_density")
            elif qty["kind"] == "unknown":
                state = "quantity_unknown"
                issues.append("quantity_not_on_label")
            else:
                state = "usable"

            if state in ("usable", "quantity_unknown") and \
                    any(h in name.upper() for h in COMPOSITE_HINTS):
                issues.append("composite_matched_to_ingredient__review")

            live = not duplicate_of
            counts = state == "usable" and live
            # Estimated tier: usable rows plus rows rescued by a declared weight.
            counts_est = live and (
                counts or (state == "quantity_unknown" and declared_g is not None)
            )

            nutrients: dict[str, float] = {}
            nutrients_est: dict[str, float] = {}
            if food in foods and live:
                if counts:
                    scale = qty["amount"] / 100.0
                    nutrients = {n: v * scale for n, v in foods[food].items()}
                if counts_est:
                    grams = qty["amount"] if counts else declared_g
                    scale = grams / 100.0
                    nutrients_est = {n: v * scale for n, v in foods[food].items()}

            items.append({
                "source_file": src,
                "duplicate_of": duplicate_of,
                "date": raw["date"],
                "year": (raw["date"] or "")[:4],
                "product_name": name,
                "food": food if action == "match" else "",
                "price": price,
                "line_type": line_type,
                "qty": qty,
                "declared_g": declared_g,
                "state": state,
                "issues": issues,
                "nutrients": nutrients,
                "nutrients_est": nutrients_est,
                "counts": counts,
                "counts_est": counts_est,
            })
    return items


def coverage(items: list[dict]) -> dict:
    live = [i for i in items if not i["duplicate_of"]]
    meta = [i for i in live if i["line_type"] == "metadata"]
    prod = [i for i in live if i["line_type"] == "product"]
    food_rows = [i for i in prod if i["food"]and i["state"] != "not_food_or_unmatched"]
    usable = [i for i in prod if i["counts"]]
    usable_est = [i for i in prod if i["counts_est"]]

    def pct(a, b):
        return round(100.0 * a / b, 1) if b else 0.0

    spend_all = sum(i["price"] or 0.0 for i in prod)
    spend_usable = sum(i["price"] or 0.0 for i in usable)
    spend_usable_est = sum(i["price"] or 0.0 for i in usable_est)

    by_state: dict[str, int] = defaultdict(int)
    for i in live:
        by_state[i["state"]] += 1

    return {
        "rows_total_raw": len(items),
        "rows_dropped_as_duplicate": len(items) - len(live),
        "rows_receipt_metadata": len(meta),
        "rows_product_lines": len(prod),
        "rows_food_matched": len(food_rows),
        "rows_usable": len(usable),
        "rows_usable_with_estimates": len(usable_est),
        "pct_matched": pct(len(food_rows), len(prod)),
        "pct_quantity_of_matched": pct(len(usable), len(food_rows)),
        "pct_usable_of_all": pct(len(usable), len(prod)),
        "pct_usable_of_all_with_estimates": pct(len(usable_est), len(prod)),
        "spend_total_eur": round(spend_all, 2),
        "spend_usable_eur": round(spend_usable, 2),
        "pct_spend_covered": pct(spend_usable, spend_all),
        "pct_spend_covered_with_estimates": pct(spend_usable_est, spend_all),
        "by_state": dict(by_state),
    }


def nutrient_density(items: list[dict], year: str | None = None,
                     mode: str = "observed") -> dict:
    """Density on the covered subset:  sum(nutrient) / sum(energy) * 2500.

    Each nutrient uses only rows where BOTH energy and that nutrient are known,
    so every figure carries its own denominator.

    mode='observed'  quantities read off the label only (headline)
    mode='estimated' also includes legacy estimated weights (sensitivity)
    """
    key = "nutrients" if mode == "observed" else "nutrients_est"
    flag = "counts" if mode == "observed" else "counts_est"
    pool = [i for i in items if i[flag] and i[key].get("Energy")]
    if year:
        pool = [i for i in pool if i["year"] == year]

    total_energy = sum(i[key]["Energy"] for i in pool)
    out: dict[str, dict] = {}
    if total_energy <= 0:
        return out

    for nut in NUTRIENT_ORDER:
        rows = [i for i in pool if nut in i[key]]
        if not rows:
            continue
        nut_energy = sum(i[key]["Energy"] for i in rows)
        amount = sum(i[key][nut] for i in rows)
        cov = 100.0 * nut_energy / total_energy
        value = amount / nut_energy * KCAL_NORM if nut_energy else None

        ref = REFERENCE.get(nut)
        top = sorted(rows, key=lambda i: i[key][nut], reverse=True)[:5]
        top_share = (top[0][key][nut] / amount * 100.0) if amount else 0.0

        out[nut] = {
            "value": round(value, 2) if value is not None else None,
            "coverage_pct": round(cov, 1),
            "reference": round(ref, 2) if ref else None,
            "reference_kind": REFERENCE_KIND.get(nut),
            "pct_of_reference": round(value / ref * 100, 1) if (ref and value) else None,
            "scored": bool(ref) and cov >= 80.0,
            "top_contributors": [
                {
                    "product_name": i["product_name"],
                    "food": i["food"],
                    "date": i["date"],
                    "amount": round(i[key][nut], 2),
                    "share_pct": round(i[key][nut] / amount * 100, 1) if amount else 0.0,
                }
                for i in top
            ],
            "dominated_by_single_item": top_share >= 25.0,
            "top_item_share_pct": round(top_share, 1),
        }
    out["_energy_pool_rows"] = len(pool)
    return out


def receipts_summary(items: list[dict]) -> dict:
    delhaize = ROOT / "data" / "delhaize"
    images = sorted(p.name for p in delhaize.glob("*.jpg")) if delhaize.exists() else []
    csvs = sorted(p for p in delhaize.glob("*.csv")) if delhaize.exists() else []
    empty = [p.name for p in csvs
             if len([l for l in p.read_text(encoding="utf-8", errors="replace").splitlines() if l.strip()]) <= 1]
    with_csv = {p.stem for p in csvs}
    no_ocr = sorted(n[:-4] for n in images if n[:-4] not in with_csv)

    in_analysis = sorted({i["source_file"] for i in items if not i["duplicate_of"]})
    return {
        "images_total": len(images),
        "images_unique": len(images) - len(DUPLICATE_ALIASES),
        "duplicate_pairs": len(DUPLICATE_ALIASES),
        "ocr_csv_files": len(csvs),
        "ocr_empty": empty,
        "images_without_ocr": no_ocr,
        "receipts_in_analysis": len(in_analysis),
        "date_first": min((i["date"] for i in items if i["date"]), default=None),
        "date_last": max((i["date"] for i in items if i["date"]), default=None),
    }


DISCLAIMER = {
    "en": ("This report describes the nutrient composition of GROCERIES BOUGHT at "
           "Delhaize, normalised to 2 500 kcal. It does not measure what anyone ate: "
           "waste, pantry stock, meals eaten out and the two retailers not yet "
           "included (Carrefour, Colruyt) are all unaccounted for."),
    "fr": ("Ce rapport décrit la composition nutritionnelle des COURSES ACHETÉES chez "
           "Delhaize, ramenée à 2 500 kcal. Il ne mesure pas ce qui a été mangé : "
           "pertes, stock de réserve, repas pris dehors et les deux enseignes pas "
           "encore intégrées (Carrefour, Colruyt) ne sont pas pris en compte."),
    "it": ("Questo report descrive la composizione nutrizionale della SPESA ACQUISTATA "
           "da Delhaize, normalizzata a 2.500 kcal. Non misura ciò che qualcuno ha "
           "mangiato: scarti, scorte in dispensa, pasti fuori casa e i due negozi non "
           "ancora inclusi (Carrefour, Colruyt) non sono considerati."),
}

# Reasons are built per language so the trust panel never mixes languages.
_REASON_TEMPLATES = {
    "usable": {
        "en": "Only {p}% of product lines are usable (matched to a food AND carrying a quantity readable on the label).",
        "fr": "Seules {p}% des lignes produit sont exploitables (associées à un aliment ET portant une quantité lisible sur l’étiquette).",
        "it": "Solo il {p}% delle righe prodotto è utilizzabile (abbinata a un alimento E con una quantità leggibile sull’etichetta).",
    },
    "lowcov": {
        "en": "{n} nutrient(s) below 80% energy coverage: {list}.",
        "fr": "{n} nutriment(s) sous 80% de couverture énergétique : {list}.",
        "it": "{n} nutriente/i sotto l’80% di copertura energetica: {list}.",
    },
    "unverified": {
        "en": "No mapping has yet been checked against an official database (CIQUAL / FoodData Central): the per-100 g values still come from the legacy pyfooda snapshot.",
        "fr": "Aucune correspondance n’a encore été vérifiée en base officielle (CIQUAL / FoodData Central) : les valeurs pour 100 g proviennent encore de l’instantané pyfooda.",
        "it": "Nessun abbinamento è ancora stato verificato su una banca dati ufficiale (CIQUAL / FoodData Central): i valori per 100 g provengono ancora dallo snapshot pyfooda legacy.",
    },
    "backlog": {
        "en": "The {a} receipts never passed to OCR and the {b} empty CSVs have not been recovered in this build — they need an API key for the reading model.",
        "fr": "Les {a} tickets jamais passés à l’OCR et les {b} CSV vides n’ont pas été récupérés ici — il faut une clé API pour le modèle de lecture.",
        "it": "I {a} scontrini mai passati all’OCR e i {b} CSV vuoti non sono stati recuperati in questa build — servono una chiave API per il modello di lettura.",
    },
}

_NUTRIENT_NAMES = {
    "en": {}, "fr": {}, "it": NUTRIENT_IT,
}


def status(cov: dict, nutrients: dict, receipts: dict) -> tuple[str, dict]:
    headline_low = [n for n, d in nutrients.items()
                    if isinstance(d, dict) and d.get("coverage_pct", 0) < 80]

    reasons: dict[str, list[str]] = {}
    for lang in ("en", "fr", "it"):
        out: list[str] = []
        if cov["pct_usable_of_all"] < 60:
            out.append(_REASON_TEMPLATES["usable"][lang].format(p=cov["pct_usable_of_all"]))
        if headline_low:
            names = ", ".join(_NUTRIENT_NAMES[lang].get(x, x) for x in headline_low)
            out.append(_REASON_TEMPLATES["lowcov"][lang].format(n=len(headline_low), list=names))
        out.append(_REASON_TEMPLATES["unverified"][lang])
        out.append(_REASON_TEMPLATES["backlog"][lang].format(
            a=len(receipts["images_without_ocr"]), b=len(receipts["ocr_empty"])))
        reasons[lang] = out

    if cov["pct_usable_of_all"] >= 85 and not headline_low:
        return "Beta", reasons
    return "Draft", reasons


def main() -> None:
    foods, units = load_food_table()
    items = build_items(foods)
    cov = coverage(items)

    years = sorted({i["year"] for i in items if i["year"]})
    nutrients_all = nutrient_density(items)
    nutrients_est = nutrient_density(items, mode="estimated")
    by_year = {y: nutrient_density(items, y) for y in years}
    by_year_est = {y: nutrient_density(items, y, mode="estimated") for y in years}

    # How much does each headline number depend on estimated (not observed)
    # quantities? Large gaps mean the figure is carried by guesses.
    sensitivity = []
    for nut in NUTRIENT_ORDER:
        a = nutrients_all.get(nut, {}).get("value")
        b = nutrients_est.get(nut, {}).get("value")
        if a and b:
            sensitivity.append({
                "nutrient": nut,
                "observed_only": a,
                "with_estimates": b,
                "delta_pct": round((b - a) / a * 100, 1),
            })
    sensitivity.sort(key=lambda d: -abs(d["delta_pct"]))

    rec = receipts_summary(items)
    state, reasons = status(cov, nutrients_all, rec)

    quarantined = defaultdict(lambda: {"rows": 0, "reason": "", "spend": 0.0})
    for i in items:
        if i["state"] == "quarantined" and not i["duplicate_of"]:
            q = quarantined[i["product_name"]]
            q["rows"] += 1
            q["reason"] = QUARANTINE[i["product_name"]]
            q["spend"] = round(q["spend"] + (i["price"] or 0.0), 2)

    unresolved = defaultdict(lambda: {"rows": 0, "state": "", "spend": 0.0})
    for i in items:
        if not i["duplicate_of"] and i["line_type"] == "product" and i["state"] in (
            "not_food_or_unmatched", "quantity_unknown", "volume_no_density"
        ):
            u = unresolved[i["product_name"]]
            u["rows"] += 1
            u["state"] = i["state"]
            u["spend"] = round(u["spend"] + (i["price"] or 0.0), 2)

    review = defaultdict(int)
    for i in items:
        if "composite_matched_to_ingredient__review" in i["issues"] and i["counts"]:
            review[f"{i['product_name']} -> {i['food']}"] += 1

    report = {
        "generated_from": "data/purchases_enriched.csv (legacy OCR snapshot)",
        "kcal_normalisation": KCAL_NORM,
        "status": state,
        "status_reasons_i18n": reasons,
        "disclaimer_i18n": DISCLAIMER,
        "disclaimer": (
            "Questo report descrive la composizione nutrizionale della SPESA "
            "ACQUISTATA da Delhaize, normalizzata a 2.500 kcal. Non misura ciò che "
            "qualcuno ha mangiato: scarti, scorte in dispensa, pasti fuori casa e i "
            "due negozi non ancora inclusi (Carrefour, Colruyt) non sono considerati."
        ),
        "nutrient_labels": NUTRIENT_IT,
        "receipts": rec,
        "coverage": cov,
        "years": years,
        "nutrients": nutrients_all,
        "nutrients_estimated": nutrients_est,
        "nutrients_by_year": by_year,
        "nutrients_by_year_estimated": by_year_est,
        "sensitivity_estimated_quantities": sensitivity,
        "units": units,
        "nutrient_order": NUTRIENT_ORDER,
        "no_reference": sorted(_NO_REFERENCE),
        "quarantined": [
            {"product_name": k, **v}
            for k, v in sorted(quarantined.items(), key=lambda kv: -kv[1]["rows"])
        ],
        "unresolved": [
            {"product_name": k, **v}
            for k, v in sorted(unresolved.items(), key=lambda kv: -kv[1]["spend"])[:120]
        ],
        "needs_review": [
            {"mapping": k, "rows": v}
            for k, v in sorted(review.items(), key=lambda kv: -kv[1])[:60]
        ],
        "items": [
            {
                "date": i["date"], "product_name": i["product_name"],
                "food": i["food"], "price": i["price"],
                "qty_amount": round(i["qty"]["amount"], 1) if i["qty"]["amount"] else None,
                "qty_unit": i["qty"]["unit"], "qty_method": i["qty"]["method"],
                "declared_g": i["declared_g"],
                "line_type": i["line_type"],
                "state": i["state"], "issues": i["issues"],
                "energy": round(i["nutrients"].get("Energy", 0), 1) or None,
            }
            # Receipt-metadata rows are included so the `receipt_metadata` state
            # filter has something to show; they carry no nutrients.
            for i in items if not i["duplicate_of"]
        ],
    }

    PUBLIC_DIR.mkdir(exist_ok=True)
    out = PUBLIC_DIR / "report.json"
    out.write_text(json.dumps(report, ensure_ascii=False, indent=1), encoding="utf-8")

    print(f"status              {state}")
    print(f"receipts analysed   {report['receipts']['receipts_in_analysis']}"
          f"  (of {report['receipts']['images_total']} images,"
          f" {report['receipts']['images_unique']} unique)")
    print(f"rows dropped (dup)  {cov['rows_dropped_as_duplicate']}")
    print(f"rows receipt meta   {cov['rows_receipt_metadata']}  (totals/points/payment)")
    print(f"rows product lines  {cov['rows_product_lines']}")
    print(f"matched             {cov['pct_matched']}%")
    print(f"quantity/matched    {cov['pct_quantity_of_matched']}%")
    print(f"usable rows         {cov['pct_usable_of_all']}%"
          f"   (with estimates {cov['pct_usable_of_all_with_estimates']}%)")
    print(f"spend covered       {cov['pct_spend_covered']}%  "
          f"(EUR {cov['spend_usable_eur']} of {cov['spend_total_eur']})")
    print(f"row states          {cov['by_state']}")
    if sensitivity:
        worst = sensitivity[0]
        print(f"most estimate-driven {worst['nutrient']}: "
              f"{worst['observed_only']} -> {worst['with_estimates']} "
              f"({worst['delta_pct']:+}%)")
    print(f"-> {out}")


if __name__ == "__main__":
    main()
